# Generated by Django 4.2.5 on 2023-10-01 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_movie_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='users_who_like',
        ),
    ]
