# Generated by Django 4.2.5 on 2023-10-01 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_remove_movie_users_who_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_img',
            field=models.CharField(default='', max_length=500),
        ),
    ]
