# Generated by Django 4.2.5 on 2023-10-02 06:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_alter_movie_movie_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
